Add podman support
These scripts now prefer podman over docker since it seems that setting
up and running containers with systemd is easier with rootless podman
than docker.

* Rename docker directory to container
* Add instructions on how to run complete scripts using podman
* Use Fedora instead of Debian container images

diff --git a/container/build-database b/container/build-database
--- a/container/build-database
+++ b/container/build-database
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Build a Docker image with the DBT-2 database created.
+# Build a Container image with the DBT-2 database created.
 
 create_cockroach()
 {
@@ -12,7 +12,7 @@ create_cockroach()
 		exit 1
 	fi
 	mkdir -p $DATADIR
-	docker run -d \
+	$ENGINE run -d \
 			--name=dbt2-cockroach-1 \
 			--hostname=dbt2-cockroach-1 \
 			-p 26257:26257 -p 8080:8080  \
@@ -20,52 +20,45 @@ create_cockroach()
 			cockroachdb/cockroach:v21.2.10 start \
 			--insecure \
 			--join=dbt2-cockroach-1,dbt2-cockroach-2,dbt2-cockroach-3
-	docker run -d \
+	$ENGINE run -d \
 			--name=dbt2-cockroach-2 \
 			--hostname=dbt2-cockroach-2 \
 			-v "${DATADIR}/roach2:/cockroach/cockroach-data"  \
 			cockroachdb/cockroach:v21.2.10 start \
 			--insecure \
 			--join=dbt2-cockroach-1,dbt2-cockroach-2,dbt2-cockroach-3
-	docker run -d \
+	$ENGINE run -d \
 			--name=dbt2-cockroach-3 \
 			--hostname=dbt2-cockroach-3 \
 			-v "${DATADIR}/roach3:/cockroach/cockroach-data"  \
 			cockroachdb/cockroach:v21.2.10 start \
 			--insecure \
 			--join=dbt2-cockroach-1,dbt2-cockroach-2,dbt2-cockroach-3
-	docker exec -it  dbt2-cockroach-1 ./cockroach init --insecure
-	IPADDRESS=$(docker inspect dbt2-cockroach-1 | jq -r '.[0].NetworkSettings.IPAddress')
-	docker run --rm -e PGHOST=$IPADDRESS -e DBT2DBNAME=dbt2 dbt2-driver \
+	$ENGINE exec -it  dbt2-cockroach-1 ./cockroach init --insecure
+	IPADDRESS=$($ENGINE inspect dbt2-cockroach-1 | jq -r '.[0].NetworkSettings.IPAddress')
+	$ENGINE run --rm -e PGHOST="$IPADDRESS" -e DBT2DBNAME=dbt2 dbt2-driver \
 			dbt2-cockroach-build-db -w $WAREHOUSES -l 26257
 	return $?
 }
 
 create_pgsql()
 {
-	which jq > /dev/null 2>&1
-	if [ $? -eq 0 ]; then
-		PGORG="https://www.postgresql.org/versions.json"
-		DBVER=`curl -s $PGORG | jq -r 'sort | .[].major' | tail -n 1`
-	fi
-	echo "Using PostgreSQL Major Version $DBVER"
-
 	TOPDIR=`dirname $0`
 
-	# Use the return code from `docker inspect` to determine if the docker image
-	# needs to be created.
-	docker inspect dbt2-base > /dev/null
+	# Use the return code from `$ENGINE inspect` to determine if the container
+	# image needs to be created.
+	$ENGINE inspect dbt2-base > /dev/null
 	if [ $? -ne 0 ]; then
 		${TOPDIR}/prepare-image || exit 1
 	fi
 
 	TOPDIR="${TOPDIR}/.."
-	docker build -t dbt2-database-${DBMS}-${WAREHOUSES}w \
-			--build-arg DBVER=$DBVER \
-			--build-arg dbms=$DBMS \
+	$ENGINE build -t "dbt2-database-${DBMS}-${WAREHOUSES}w" \
+			$ENGINEARGS \
 			--build-arg warehouses=$WAREHOUSES \
 			--shm-size=128m \
-			-f Dockerfile.database $TOPDIR
+			-f Containerfile.database \
+			"$TOPDIR"
 	return $?
 }
 
@@ -78,28 +71,36 @@ create_yugabyte()
 		exit 1
 	fi
 	mkdir -p $DATADIR
-	docker run -d --name dbt2-yugabyte \
+	$ENGINE run -d --name dbt2-yugabyte \
 			-p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042 \
 			-v ${DATADIR}:/home/yugabyte/yb_data \
 			yugabytedb/yugabyte:latest bin/yugabyted start \
 			--base_dir=/home/yugabyte/yb_data --daemon=false
 	# We need to wait for Yugabyte to finish starting up before trying to load.
 	sleep 10
-	IPADDRESS=$(docker inspect dbt2-yugabyte | jq -r '.[0].NetworkSettings.IPAddress')
-	docker run --rm -e PGHOST=$IPADDRESS -e DBT2DBNAME=dbt2 -e PGUSER=postgres \
+	IPADDRESS=$($ENGINE inspect dbt2-yugabyte | jq -r '.[0].NetworkSettings.IPAddress')
+	$ENGINE run --rm -e PGHOST="$IPADDRESS" -e DBT2DBNAME=dbt2 -e PGUSER=postgres \
 			dbt2-driver dbt2-yugabyte-build-db -w $WAREHOUSES -l 5433
 	return $?
 }
 
-which docker > /dev/null 2>&1
-if [ $? -ne 0 ]; then
-	echo "docker not in path"
-	exit 1
+ENGINE="podman"
+if ! which $ENGINE > /dev/null 2>&1; then
+	ENGINE="docker"
+	if ! which $ENGINE > /dev/null 2>&1; then
+		echo "podman nor docker in path"
+		exit 1
+	fi
+fi
+
+echo "using container enginer: $ENGINE"
+
+if [ "$ENGINE" = "podman" ]; then
+	ENGINEARGS="--isolation=chroot"
 fi
 
 WAREHOUSES=1
 DBMS="pgsql"
-DBVER=13
 
 if [ $# -ge 1 ]; then
 	WAREHOUSES=$1
diff --git a/container/start-driver b/container/start-driver
--- a/container/start-driver
+++ b/container/start-driver
@@ -7,10 +7,20 @@ usage()
 	echo "usage: $0 <client address> [WAREHOUSES [DURATION [WAREHOUSE_MIN [WAREHOUSE_MAX]]]]"
 }
 
-which docker > /dev/null 2>&1
-if [ $? -ne 0 ]; then
-	echo "docker not in path"
-	exit 1
+ENGINE="podman"
+if ! which $ENGINE > /dev/null 2>&1; then
+	ENGINE="docker"
+	if ! which $ENGINE > /dev/null 2>&1; then
+		echo "podman nor docker in path"
+		exit 1
+	fi
+fi
+
+if [ "$ENGINE" = "podman" ]; then
+	# Sometimes it's "podman", sometimes "cni-podman0".
+	PODMANNETWORK=$(podman network ls -q | grep podman | head -n 1)
+	echo "using podman network: $PODMANNETWORK"
+	ENGINEARGS="--network=$PODMANNETWORK"
 fi
 
 if [ $# -lt 1 ]; then
@@ -18,8 +28,8 @@ if [ $# -lt 1 ]; then
 	exit 1
 fi
 
-DOCKER_NAME="dbt2-driver-${WAREHOUSES}w"
-DOCKER_TAG="dbt2-driver"
+CONTAINER_NAME="dbt2-driver-${WAREHOUSES}w"
+CONTAINER_TAG="dbt2-driver"
 WAREHOUSES=1
 WMIN=1
 WMAX=1
@@ -45,13 +55,13 @@ if [ $# -ge 5 ]; then
 	WMAX=$5
 fi
 
-DOCKERDIR=`dirname $0`
+CONTAINERDIR=$(dirname "$0")
 
-# Use the return code from `docker inspect` to determine if the docker image
-# needs to be created.
-docker inspect $DOCKER_TAG > /dev/null
+# Use the return code from `$ENGINE inspect` to determine if the container
+# image needs to be created.
+$ENGINE inspect $CONTAINER_TAG > /dev/null
 if [ $? -ne 0 ]; then
-	${DOCKERDIR}/build-driver || exit 1
+	"${CONTAINERDIR}/build-driver" || exit 1
 fi
 
 if [ ! "x$VERBOSE" = "x1" ]; then
@@ -63,8 +73,11 @@ if [ ! "x$VERSION" = "x2" ]; then
 fi
 
 NO_THINK_TIME="-ktd 0 -ktn 0 -kto 0 -ktp 0 -kts 0 -ttd 0 -ttn 0 -tto 0 -ttp 0 -tts 0"
-docker run --rm --name $DOCKER_NAME \
-		$DOCKER_TAG \
+$ENGINE run \
+		$ENGINEARGS \
+		--rm \
+		--name "$CONTAINER_NAME" \
+		$CONTAINER_TAG \
 		bash -c "dbt2-driver${VERSION} -d $HOST -wmin $WMIN -wmax $WMAX -w $WAREHOUSES -l $TEST_LENGTH $NO_THINK_TIME -sleep 100 -outdir /tmp && if [ "x$VERSION" = "x2" ]; then cat /tmp/mix-*.log > /tmp/mix.log; fi &&  VERBOSE=${VERBOSE} dbt2-post-process /tmp/mix.log"
 if [ $? -ne 0 ]; then
 	usage
