pgsql: refactor build-db and load-db scripts
Move the of all logic of loading tables back into the load-db script.

diff --git a/src/scripts/pgsql/dbt2-pgsql-load-db b/src/scripts/pgsql/dbt2-pgsql-load-db
--- a/src/scripts/pgsql/dbt2-pgsql-load-db
+++ b/src/scripts/pgsql/dbt2-pgsql-load-db
@@ -1,10 +1,10 @@
 #!/bin/sh
-
 #
 # This file is released under the terms of the Artistic License.
 # Please see # the file LICENSE, included in this package, for details.
 #
-# Copyright (C) 2002-2008 Mark Wong & Open Source Development Labs, Inc.
+# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
+# Copyright (C) 2002-2021 Mark Wong
 #
 
 if [ -z ${DBT2DBNAME} ]; then
@@ -12,85 +12,93 @@ if [ -z ${DBT2DBNAME} ]; then
 	exit 1
 fi
 
-BACKGROUND="no"
-
 usage()
 {
-	echo "usage: `basename $0` -d <dir> [-b] [-l <port>] [-t]"
-	echo "  <dir> is where the data files are."
+	echo "Usage:"
+	echo "    `basename $0` [options]"
+	echo "    `basename $0` -h"
+	echo "Options:"
+	echo "    -l <PORT>"
+	echo "        PostgreSQL port"
+	echo "    -s <SEED>"
+	echo "        User defined functions to install, default: c"
+	echo "    -w <WAREHOUSES>"
+	echo "        Number of warehouses to build. Default 1."
 }
 
-while getopts "bd:l:t" OPT; do
+SEED=""
+WAREHOUSES=1
+while getopts "l:s:w:" OPT; do
 	case ${OPT} in
-	b)
-		BACKGROUND="yes"
-		;;
-	d)
-		DBDATA="`dirname ${OPTARG}`/`basename ${OPTARG}`"
-		;;
 	l)
 		PORT=${OPTARG}
 		;;
-	t)
-		TABLESPACES_FLAG="-t"
+	s)
+		SEED=$OPTARG
+		;;
+	w)
+		WAREHOUSES=$OPTARG
 		;;
 	esac
 done
-
-if [ "x${DBDATA}" = "x" ]; then
-	usage
-	exit 1
-fi
 
 if [ ! "x${PORT}" = "x" ]; then
 	PORTARG="-p ${PORT}"
 fi
 
-# Load tables
-# This background stuff is honestly kinda ugly. IMO the right way to do this
-# is to utilize make -j
-
-load_table2() {
-	$1 "$2" || exit 1
-	$1 "$3" || exit 1
-}
+# Generate a seed randomly if one is not provided.
+if [ "x${SEED}" = "x" ]; then
+	SEED=`dbt2-rand -1 1 15`
+fi
 
 load_table() {
-	table=$1
-	if [ "x$2" == "x" ]; then
-		file=$table.data
-	else
-		file=$2.data
+	local TABLE=$1
+	local WAREHOUSES=$2
+	local SEED=$3
+
+	# Detect the number of processors to determining how much to parallelize the
+	# data loading.  Otherwise arbitrarily use 2 processes.  The item table is
+	# always parallelizable.
+	local CPUS=2
+	if [ -f "/proc/stat" ]; then
+		CPUS=`grep cpu /proc/stat | wc -l`
+		CPUS=$(( $CPUS - 1 ))
+		if [ ! "x$TABLE" = "xitem" ] && [ $WAREHOUSES -eq 1 ]; then
+			# Don't parallelize the load if there is only 1 warehouse.
+			CPUS=1
+		elif [ ! "x$TABLE" = "xitem" ] && [ $WAREHOUSES -lt $CPUS ]; then
+			# Don't parallelize more than the number of warehouses if there are
+			# less warehouses to build than the number of processors available.
+			CPUS=$WAREHOUSES
+		else
+			echo "detected $CPUS processors for parallel loading"
+		fi
 	fi
 
-	local sql="COPY $table FROM '${DBDATA}/$file' WITH NULL AS '';"
-	local cmd="psql -X ${PORTARG} -e -d ${DBT2DBNAME} -c "
-	if [ "${BACKGROUND}" == "yes" ]; then
-		echo "Loading $table table in the background..."
-		load_table2 "${cmd}" "${sql}" "VACUUM ANALYZE $table;" &
-	else
-		echo "Loading $table table..."
-		${cmd} "${sql}" || exit 1
+	for i in `seq 1 $CPUS`; do
+		run_datagen $CPUS $i $TABLE $WAREHOUSES $SEED &
+	done
+	wait
+}
+
+run_datagen()
+{
+	local TOTAL=$1
+	local PART=$2
+	local TABLE=$3
+	local WAREHOUSES=$4
+	local SEED=$5
+
+	dbt2-datagen --direct -w $WAREHOUSES --pgsql --table $TABLE --seed $SEED \
+			-P $TOTAL -p $PART
+	if [ $? -ne 0 ]; then
+		echo "ERROR: datagen couldn't load part $PART of $TOTAL with $TABLE"
+		exit 1
 	fi
 }
 
-load_table customer
-load_table district
-load_table history
-load_table item
-load_table new_order
-load_table order_line
-load_table orders order
-load_table stock
-load_table warehouse
-
-wait
-
-# load C or pl/pgsql implementation of the stored procedures
-#if true; then
-#  ${DIR}/dbt2-pgsql-load-stored-procs -l ${PORT} -t c|| exit 1
-#else
-#  ${DIR}/dbt2-pgsql-load-stored-procs -l ${PORT} -t plpgsql || exit 1
-#fi
-
-exit 0
+# Load one table at a time, but each table load will be parallelized.
+for TABLE in item warehouse stock district customer history orders new_order;
+do
+	load_table $TABLE $WAREHOUSES $SEED
+done
