[project @ 1489] Reworked the scripts to source scripts/dbt2_profile instead of pgsql_profile in order to share variables with other scripts.

diff --git a/scripts/pgsql/backup.sh.in b/scripts/pgsql/backup.sh.in
--- a/scripts/pgsql/backup.sh.in
+++ b/scripts/pgsql/backup.sh.in
@@ -1,14 +1,14 @@
-#!/bin/sh
-
+#!/bin/bash
 #
 # This file is released under the terms of the Artistic License.
 # Please see the file LICENSE, included in this package, for details.
 #
-# Copyright (C) 2002 Mark Wong & Open Source Development Lab, Inc.
+# Copyright (C) 2002-2006 Mark Wong & Open Source Development Labs, Inc.
 #
 
-DIR=`dirname $0`
-. ${DIR}/pgsql_profile || exit 1
+
+TOPDIR="@abs_top_srcdir@"
+source ${TOPDIR}/scripts/dbt2_profile || exit 1
 
 while getopts "o:" opt; do
 	case $opt in
@@ -23,9 +23,9 @@ if [ "$OUTPUT" == "" ]; then
 	exit 1;
 fi
 
-_test=`$PGRESTORE -v Fc -a -d $DBNAME $OUTPUT | grep OK`
+_test=`pg_dump $DBNAME --file=$OUTPUT | grep OK`
 if [ "$_test" != "" ]; then
-	echo "restore failed: $_test"
+	echo "backup failed: $_test"
 	exit 1
 fi
 
