Add version flag to AppRun and version script

diff --git a/appimage/AppRun.in b/appimage/AppRun.in
--- a/appimage/AppRun.in
+++ b/appimage/AppRun.in
@@ -1,4 +1,5 @@
 #!/bin/sh
+@SHELLOPTIONS@
 
 usage() {
 	# Note that $0 return AppRun, as opposed to the AppImage filename.
@@ -15,14 +16,37 @@ Options:
 Commands:
 $(find "${APPDIR}/usr/bin" -maxdepth 1 -type f -name "dbt2-*" -printf "%f\n" | sed -e "s/dbt2-/  /")
 
-Database Test 2 (DBT-2) project page: https://github.com/osdldbt/dbt2
+@HOMEPAGE@
 EOF
 }
 
 if [ $# -eq 0 ]; then
 	usage
-	exit 0
+	exit 1
 fi
+
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(-V | --version)
+		echo "dbt2 (Database Test 2) v@PROJECT_VERSION@"
+		exit 0
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
+		;;
+	esac
+	shift
+done
 
 # We need a writable location before the read-only location in the AppImage.
 # ${HOME}/.julia is the default location.
